### ISSUE TITLE
Cannot enroll new user

### ISSUE THREAD

**Issue by abhijitnathwani** [natsu90/whoiscomingto.party#1]
Hi,

While trying out this awesome project on the demo link provided, i could enroll as a new user.
The `enroll` page does not load.
![image](https://user-images.githubusercontent.com/5513984/76748337-9591a580-67a0-11ea-82f3-9d80dd13f2f2.png)

Let me know the workaround, if any.

**Comment by natsu90** [comment]
Can you try again? This is due to flooded traffic since I was on free plan Firebase.
